### ISSUE TITLE
fix ee_ariregister

### ISSUE THREAD

**Issue by simonwoerpel** [opensanctions/graph#14]
Fix memory problems with json parsing in ee_ariregister.
try: https://pypi.org/project/ijson/

**Comment by simonwoerpel** [comment]
https://github.com/opensanctions/graph/pull/19

**Comment by pudo** [comment]
@simonwoerpel this is fully done, right?

**Comment by simonwoerpel** [comment]
yes

**Comment by simonwoerpel** [comment]
aah, but there is another thing about estland: https://github.com/opensanctions/graph/issues/22
can do this today

**Comment by simonwoerpel** [comment]
this is now solved: https://github.com/opensanctions/graph/pull/24
