### ISSUE TITLE
make a shell script for upload

### ISSUE THREAD

**Issue by pudo** [opensanctions/graph#16]
Right now, we're using this command invocation to upload the resulting artifacts:

```bash
aws s3 sync --no-progress --cache-control "public, max-age=64600" --metadata-directive REPLACE --acl public-read data/export s3://data.opensanctions.org/graph/icij_offshoreleaks
```

I would like to replace this with a call to a common shell script, like this:

```bash
bash ../../scripts/upload.sh icij_offshoreleaks data/export 
```

In that script we can then add cloudfront cache invalidation and content-disposition headers for the data

**Comment by simonwoerpel** [comment]
https://github.com/opensanctions/graph/pull/18
